### ISSUE TITLE
i cant test locally your webapp

### ISSUE THREAD

**Issue by johnfelipe** [SumonRayy/ibm-watson-language-translator-client#1]
Language Translator
Loading...

![SNAG-1189](https://user-images.githubusercontent.com/428820/172034522-0685371a-7355-4e87-8910-2aa110dca1c1.png)

	Compiled successfully!

	You can now view client in the browser.

	  http://localhost:3000

	Note that the development build is not optimized.
	To create a production build, use yarn build.

	assets by path static/js/*.js 1.49 MiB
	  asset static/js/bundle.js 1.49 MiB [emitted] (name: main) 1 related asset
	  asset static/js/node_modules_web-vitals_dist_web-vitals_js.chunk.js 6.92 KiB [emitted] 1 related asset
	asset index.html 1.67 KiB [emitted]
	asset asset-manifest.json 458 bytes [emitted]
	runtime modules 31.3 KiB 15 modules
	modules by path ./node_modules/ 1.35 MiB 99 modules
	modules by path ./src/ 25.1 KiB
	  modules by path ./src/*.css 12 KiB
		./src/index.css 2.72 KiB [built] [code generated]
		./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[5].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[5].use[2]!./node_modules/source-map-loader/dist/cjs.js!./src/index.css 1.37 KiB [built] [code generated]
		./src/App.css 2.72 KiB [built] [code generated]
		./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[5].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[5].use[2]!./node_modules/source-map-loader/dist/cjs.js!./src/App.css 5.16 KiB [built] [code generated]
	  modules by path ./src/*.js 4.95 KiB
		./src/index.js 1.8 KiB [built] [code generated]
		./src/App.js 1.75 KiB [built] [code generated]
		./src/reportWebVitals.js 1.4 KiB [built] [code generated]
	  ./src/components/Translator.js 8.16 KiB [built] [code generated]
	webpack 5.68.0 compiled successfully in 5661 ms

**Comment by SumonRayy** [comment]
@johnfelipe have you used your own watson api key? If you haven't then please login to your Watson account and paste the key in a ```.env``` file. I hope this will solve your issue 

Learn more at here : 
https://www.ibm.com/in-en/cloud/watson-language-translator

**Comment by johnfelipe** [comment]
pls share format of .env file pls

**Comment by SumonRayy** [comment]
Simply just
1. Create `.env` file on the root directory
2. Inside `.env` file write environment variable in this format: 
     ```
      REACT_SERVER_URL = "/*Your Api Key Url*/"
     ```
I hope this will solve your issue 😇

Edit : hope your issue has been solved , so I'm Closing this issue and I'll update the readme for better understanding, If you still face some issue then let me know 😇🙏🏼 thanks for checking
